[package]
name = "visa_ex_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "visa_ex_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
sys = "0.0.0"
visa-rs = "0.4.0"
